### ISSUE TITLE
Crash upon dropping the dank. [1.16]

### ISSUE THREAD

**Issue by Famous5000** [Tfarcenim/Dank-Storage#110]
```
java.lang.ClassCastException: net.minecraft.item.AirItem cannot be cast to tfar.dankstorage.item.DankItem
	at tfar.dankstorage.utils.Utils.getStats(Utils.java:82) ~[?:3.16] {re:mixin,re:classloading}
	at tfar.dankstorage.inventory.PortableDankHandler.<init>(PortableDankHandler.java:18) ~[?:3.16] {re:classloading}
	at tfar.dankstorage.utils.Utils.getHandler(Utils.java:170) ~[?:3.16] {re:mixin,re:classloading}
	at tfar.dankstorage.utils.Utils.getHandler(Utils.java:166) ~[?:3.16] {re:mixin,re:classloading}
	at tfar.dankstorage.item.DankItem$1.lambda$getCapability$0(DankItem.java:72) ~[?:3.16] {re:classloading}
	at tfar.dankstorage.item.DankItem$1$$Lambda$11774/1520353915.get(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.getValue(LazyOptional.java:122) ~[?:?] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:163) ~[?:?] {re:classloading}
	at com.github.lehjr.numina.util.client.render.RenderGameOverlayEventHandler.drawModeChangeIcons(RenderGameOverlayEventHandler.java:65) ~[?:2.0.5] {re:classloading,pl:runtimedistcleaner:A}
	at com.github.lehjr.numina.util.client.render.RenderGameOverlayEventHandler.onPostRenderGameOverlayEvent(RenderGameOverlayEventHandler.java:56) ~[?:2.0.5] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_471_RenderGameOverlayEventHandler_onPostRenderGameOverlayEvent_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2533/218640634.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:832) ~[?:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238443_a_(ForgeIngameGui.java:365) ~[?:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:149) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:472) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.42.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$476/700631078.call(Unknown Source) [forge-1.16.5-36.0.42.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
```

**Comment by Famous5000** [comment]
Note: This was with Numia installed, as you helpfully pointed out in the discord. Doing some final testing to see if dropping w/o that mod will cause the issue...

**Comment by Famous5000** [comment]
CLOSED: Not an issue with DANK.
Will report this to Numina when I get the chance.
