### ISSUE TITLE
[Client] Breeding causes java.lang.RuntimeException: Attempted to get inventory error on client

### ISSUE THREAD

**Issue by lwskosa** [Tfarcenim/Dank-Storage#147]
# To reproduce this issue:

1. Add breeding material to storage [Wheat]
2. Switch Dank to Construction mode
3. Right click on mob [Cow] to initiate Love Mode
4. Client crashes to Launcher with Exit code -1

Additional notes:
* Server is unaffected

[Pastebin to log](https://pastebin.com/hpmFEgxG)

Log:
`java.lang.RuntimeException: Attempted to get inventory on client
	at tfar.dankstorage.utils.Utils.getInventory(Utils.java:234)
	at tfar.dankstorage.item.DankItem.method_7847(DankItem.java:166)
	at net.minecraft.class_1799.method_7920(class_1799.java:398)
	at net.minecraft.class_1657.method_7287(class_1657.java:1072)
	at net.minecraft.class_636.method_2905(class_636.java:394)
	at net.minecraft.class_310.method_1583(class_310.java:1631)
	at net.minecraft.class_310.method_1508(class_310.java:1900)
	at net.minecraft.class_310.method_1574(class_310.java:1728)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at tfar.dankstorage.utils.Utils.getInventory(Utils.java:234)
	at tfar.dankstorage.item.DankItem.method_7847(DankItem.java:166)
	at net.minecraft.class_1799.method_7920(class_1799.java:398)
	at net.minecraft.class_1657.method_7287(class_1657.java:1072)
	at net.minecraft.class_636.method_2905(class_636.java:394)
	at net.minecraft.class_310.method_1583(class_310.java:1631)
	at net.minecraft.class_310.method_1508(class_310.java:1900)`

**Comment by lwskosa** [comment]
Wrong version, meant to post this to Fabric. My apologies.

**Comment by lwskosa** [comment]
Wrong version, meant to post this to Fabric. My apologies.
