### ISSUE TITLE
Items get deleted for no reason.

### ISSUE THREAD

**Issue by daMathHatter** [Tfarcenim/Dank-Storage#151]
I've been playing All Of Fabric 5 in 1.18.1, and in the tier 3 dank, the bottom row auto deletes everything set into it when I open and close my inventory.
![2021-12-20_20 59 41](https://user-images.githubusercontent.com/82483471/146868786-79372460-cf8a-4a27-9ac9-3f0055856dd5.png)
![2021-12-20_20 59 44](https://user-images.githubusercontent.com/82483471/146868808-67721074-3fab-4a23-81f3-0f5270a722dc.png)
![2021-12-20_20 59 45](https://user-images.githubusercontent.com/82483471/146868814-92003fba-c169-411b-aee2-77510680a357.png)

I tried replicating it outside of this world and it doesn't seem to work. It is not in void pickup mode or anything, just destorys items.

**Comment by Tfarcenim** [comment]
> I tried replicating it outside of this world and it doesn't seem to work.

Does this mean it wasn't reproducible on a fresh world, or that it still had the same problem on a fresh world?

**Comment by daMathHatter** [comment]
It was not reproducible in a fresh world.

**Comment by ryepulsar** [comment]
I have the same issue, this shows up in the server log when using my dank 2:
```
java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9
	at java.util.Arrays$ArrayList.set(Arrays.java:4170) ~[?:?]
	at net.minecraft.class_2371.set(class_2371.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_1277.method_5447(class_1277.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.class_1735.method_7673(class_1735.java:61) ~[server-intermediary.jar:?]
	at tfar.dankstorage.container.AbstractDankMenu.method_7593(AbstractDankMenu.java:219) ~[dankstorage-3.1-1.18.1.jar:?]
	at net.minecraft.class_3244.method_12076(class_3244.java:1400) ~[server-intermediary.jar:?]
	at net.minecraft.class_2813.method_12191(class_2813.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_2813.method_11054(class_2813.java:13) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
and this if i put more than 256 in one slot:
```
[21:58:25] [Server thread/FATAL]: Error executing task on Server
java.lang.ArrayIndexOutOfBoundsException: null
```
