### ISSUE TITLE
Dank docks crashing world

### ISSUE THREAD

**Issue by ADerpynarwhal** [Tfarcenim/Dank-Storage#235]
Hey! I've been playing on a multiplayer server with my siblings and we recently added danks as a part of our modpack. I was using a smart chute from the create mod to transport items into/out of docked danks. They have itemHandler tags so I figured it'd work fine. As soon as I put a dank into the dock, my game crashed and force closed. Reloading a new session, logging into the world immediately closes the game. I have reproduced the bug successfully in singleplayer multiple times so I know it's not a one-off. Placing a chute above a docked dank(or docking a dank below a chute in this case) will instantly crash the server. I've looked up resources and found that other people have had similar issues with danks in the "All the mods" modpack. https://github.com/AllTheMods/ATM-9/issues/709

Is there a way to fix this and recover the save, or a patch that can be implemented? I'll link the crash report below

```---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-03-01 19:20:23
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3847(net.minecraft.class_5321)" because "server" is null
	at tfar.dankstorage.DankStorage.getData(DankStorage.java:69)
	at tfar.dankstorage.blockentity.CommonDockBlockEntity.getInventory(CommonDockBlockEntity.java:94)
	at tfar.dankstorage.blockentity.DockBlockEntity.getStorage(DockBlockEntity.java:28)
	at net.fabricmc.fabric.api.lookup.v1.block.BlockApiLookup.lambda$registerForBlockEntity$0(BlockApiLookup.java:221)
	at net.fabricmc.fabric.impl.lookup.block.BlockApiLookupImpl.lambda$registerForBlockEntities$1(BlockApiLookupImpl.java:160)
	at net.fabricmc.fabric.impl.lookup.block.BlockApiLookupImpl.find(BlockApiLookupImpl.java:90)
	at io.github.fabricators_of_create.porting_lib.transfer.TransferUtil.getItemStorage(TransferUtil.java:130)
	at io.github.fabricators_of_create.porting_lib.transfer.internal.cache.ClientItemLookupCache.find(ClientItemLookupCache.java:58)
	at io.github.fabricators_of_create.porting_lib.transfer.internal.cache.ClientItemLookupCache.find(ClientItemLookupCache.java:25)
	at net.fabricmc.fabric.api.lookup.v1.block.BlockApiCache.find(BlockApiCache.java:55)
	at io.github.fabricators_of_create.porting_lib.util.StorageProvider$CachedStorageProvider.get(StorageProvider.java:116)
	at com.simibubi.create.content.logistics.chute.ChuteBlockEntity.grabCapability(ChuteBlockEntity.java:509)
	at com.simibubi.create.content.logistics.chute.ChuteBlockEntity.handleDownwardOutput(ChuteBlockEntity.java:363)
	at com.simibubi.create.content.logistics.chute.ChuteBlockEntity.tick(ChuteBlockEntity.java:169)
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_638.method_18116(class_638.java:259)
	at net.minecraft.class_310.method_1574(class_310.java:1901)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at tfar.dankstorage.DankStorage.getData(DankStorage.java:69)
	at tfar.dankstorage.blockentity.CommonDockBlockEntity.getInventory(CommonDockBlockEntity.java:94)
	at tfar.dankstorage.blockentity.DockBlockEntity.getStorage(DockBlockEntity.java:28)
	at net.fabricmc.fabric.api.lookup.v1.block.BlockApiLookup.lambda$registerForBlockEntity$0(BlockApiLookup.java:221)
	at net.fabricmc.fabric.impl.lookup.block.BlockApiLookupImpl.lambda$registerForBlockEntities$1(BlockApiLookupImpl.java:160)
	at net.fabricmc.fabric.impl.lookup.block.BlockApiLookupImpl.find(BlockApiLookupImpl.java:90)
	at io.github.fabricators_of_create.porting_lib.transfer.TransferUtil.getItemStorage(TransferUtil.java:130)
	at io.github.fabricators_of_create.porting_lib.transfer.internal.cache.ClientItemLookupCache.find(ClientItemLookupCache.java:58)
	at io.github.fabricators_of_create.porting_lib.transfer.internal.cache.ClientItemLookupCache.find(ClientItemLookupCache.java:25)
	at net.fabricmc.fabric.api.lookup.v1.block.BlockApiCache.find(BlockApiCache.java:55)
	at io.github.fabricators_of_create.porting_lib.util.StorageProvider$CachedStorageProvider.get(StorageProvider.java:116)
	at com.simibubi.create.content.logistics.chute.ChuteBlockEntity.grabCapability(ChuteBlockEntity.java:509)
	at com.simibubi.create.content.logistics.chute.ChuteBlockEntity.handleDownwardOutput(ChuteBlockEntity.java:363)
	at com.simibubi.create.content.logistics.chute.ChuteBlockEntity.tick(ChuteBlockEntity.java:169)
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_638.method_18116(class_638.java:259)

-- Block entity being ticked --
Details:
	Name: create:smart_chute // com.simibubi.create.content.logistics.chute.SmartChuteBlockEntity
	Block: Block{create:smart_chute}[powered=false]
	Block location: World: (50,94,4), Section: (at 2,14,4 in 3,5,0; chunk contains blocks 48,-64,0 to 63,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Block: Block{create:smart_chute}[powered=false]
	Block location: World: (50,94,4), Section: (at 2,14,4 in 3,5,0; chunk contains blocks 48,-64,0 to 63,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_638.method_18116(class_638.java:259)
	at net.minecraft.class_310.method_1574(class_310.java:1901)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 2 total; [class_746['ADerpyNarwhal'/1283168, l='ClientLevel', x=49.24, y=93.00, z=5.60], class_745['_Xndi_'/302391, l='ClientLevel', x=138.24, y=118.00, z=59.30]]
	Chunk stats: 4096, 1074
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,117,0), Section: (at 0,5,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 82243340 game time, 1265 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/Whimzee's Better Desert Pyramid - RESOURCE PACK, file/Whimzee's Better Jungle Temple - RESOURCE PACK

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 302137200 bytes (288 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900X 12-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2582
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3623
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 32768.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 32768.00
	Memory slot #3 clockSpeed (GHz): 2.67
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 86963.08
	Virtual memory used (MB): 54199.88
	Swap memory total (MB): 5120.00
	Swap memory used (MB): 135.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ad_astra: Ad Astra 1.15.5
		animated_guns: Simple Animated Guns 1.3
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
		azurelib: AzureLib 2.0.6
		botarium: Botarium 2.3.2
			team_reborn_energy: Energy 3.0.0
		create: Create 0.5.1-d-build.1161+mc1.20.1
			com_electronwill_night-config_core: core 3.6.3
			com_electronwill_night-config_toml: toml 3.6.3
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.9-1
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20
			porting_lib_base: Porting Lib Base 2.1.1127+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
			porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20
			porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20
				mm: Manningham Mills 2.3
				porting_lib_core: Porting Lib Core 2.1.1127+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
			porting_lib_entity: Porting Lib Entity 2.1.1127+1.20
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20
			porting_lib_models: Porting Lib Models 2.1.1127+1.20
			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20
				porting_lib_common: Porting Lib Common 2.1.1127+1.20
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20
			porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		dankstorage: Dank Storage 7
		fabric-api: Fabric API 0.88.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.3+92a0d36777
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.3+6bdb2ed077
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+195226a777
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.24
		immersive_aircraft: Immersive Aircraft 0.5.1+1.20.1
		indium: Indium 1.0.21+mc1.20.1
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		litematica: Litematica 0.15.3
		malilib: MaLiLib 0.16.3
		minecraft: Minecraft 1.20.1
		resourcefulconfig: Resourcefulconfig 2.1.2
		resourcefullib: Resourceful Lib 2.1.23
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		smallships: Small Ships 2.0.0-b1.0
		sodium: Sodium 0.4.10+build.27
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		xaerominimap: Xaero's Minimap 23.9.3
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.14.24-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3050/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.23, NVIDIA Corporation
	Window size: 1440x829
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated.' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Whimzee's Better Desert Pyramid - RESOURCE PACK (incompatible), file/Whimzee's Better Jungle Temple - RESOURCE PACK (incompatible)
	Current Language: en_us
	CPU: 24x AMD Ryzen 9 5900X 12-Core Processor ```

**Comment by Tfarcenim** [comment]
fixed in 1.20.1-9
