### ISSUE TITLE
Mod indicates 1.21.1 but loads as 1.21 [FABRIC]

### ISSUE THREAD

**Issue by Blinkrupt** [Tfarcenim/Dank-Storage#252]
Title says it all, here is the copied error:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'DankStorage' (dankstorage) 2 with any version that is compatible with:
		 - minecraft 1.21.1
More details:
	 - Mod 'DankStorage' (dankstorage) 2 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Blinkrupt** [comment]
The latest update fixed this issue, thanks!
