### ISSUE TITLE
Crashing when trying to right-click with item [Dank Storage 1.21.1-5 Fabric]

### ISSUE THREAD

**Issue by jshipley** [Tfarcenim/Dank-Storage#266]
When trying to right-click with an item while Dank Storage is installed, Minecraft crashes. This is happening on a fresh world created in Minecraft 1.21.1

Mods installed:
* Fabric API 0.104.0+1.21.1
* Cloth Config 15.0.140
* DankStorage 5

```
    [21:15:19] [Render thread/ERROR]: Unreported exception thrown!
    java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1271.method_5467()" because "result" is null
	at net.fabricmc.fabric.api.event.player.UseItemCallback.lambda$static$0(UseItemCallback.java:44) ~[fabric-events-interaction-v0-0.7+ba9dae0619-c776e3aa5517dbe5.jar:?]
	at net.minecraft.class_636.handler$zdm000$fabric-events-interaction-v0$interactItem(class_636.java:710) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_2919(class_636.java:375) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1583(class_310.java:1872) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:2111) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1938) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1246) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
```

Full log: https://mclo.gs/YPTynT5

**Comment by Tfarcenim** [comment]
Fixed in 1.21.1-6
