### ISSUE TITLE
1.21.1 Game Crash

### ISSUE THREAD

**Issue by wHazem** [Tfarcenim/Dank-Storage#277]
Game Crashed when collecting blocks with Dank Storage

**Setup**
- Minecraft: 1.21.1
- Fabric: 0.16.9
- Dank Storage: 1.21.1-11

---- Minecraft Crash Report ----
// You're mean.

Time: 2024-12-01 20:27:29
Description: Exception in server tick loop

java.lang.IllegalStateException: Value must be within range [1;99]: 3493
	at knot//com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287)
	at knot//com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81)
	at knot//net.minecraft.class_1799.method_57376(class_1799.java:396)
	at knot//tfar.dankstorage.inventory.DankInventory.save(DankInventory.java:468)
	at knot//tfar.dankstorage.world.DankSavedData.method_75(DankSavedData.java:37)
	at knot//net.minecraft.class_18.method_17919(class_18.java:42)
	at knot//net.minecraft.class_26.method_32384(class_26.java:127)
	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
	at knot//net.minecraft.class_26.method_125(class_26.java:125)
	at knot//net.minecraft.class_3218.method_14188(MixinServerLevel.java:833)
	at knot//net.minecraft.class_3218.method_14176(MixinServerLevel.java:815)
	at knot//net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:556)
	at knot//net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:580)
	at knot//net.minecraft.class_1132.method_39218(class_1132.java:318)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:924)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Tfarcenim** [comment]
fixed in 1.21.1-12
