### ISSUE TITLE
[1.14.4] IndexOutOfBounds

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [Tfarcenim/Dank-Storage#30]
net.minecraft.crash.ReportedException: Rendering overlay
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:548) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) ~[1.14.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.14.4-28.1.79.jar:28.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_221]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_221]
	at com.tfar.dankstorage.client.Client.models(Client.java:75) ~[?:1.10a]

**Comment by Tfarcenim** [comment]
modlist, and steps to reproduce

**Comment by Tfarcenim** [comment]
Hmm, the only way that could cause an indexoutofbounds is if another mod crashed earlier and killed the eventbus, so yeah, full logs

**Comment by Rumpelstiltskinny** [comment]
Yeah, it was another mod. False alarm. Sorry for the trouble.

**Comment by Birgliss** [comment]
do you happen to know what mod was causing this? i'm getting a very similar crash report and i'm not sure how to fix it
