### ISSUE TITLE
1.15.2 dank storage 2.5 crashes minecraft

### ISSUE THREAD

**Issue by Seegras** [Tfarcenim/Dank-Storage#42]
On 115.2 and forge-1.15.2-31.1.1 dank storage 2.5 immediately crashes minecraft. 
Of course it could be some interaction between mods, but all other 165 mods here work together, with forge-1.15.2-31.1.1 and forge-1.15.2-31.1.9 as well. 

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 15/02/20 11:26
Description: Initializing game

java.lang.NullPointerException: Registry Object not present
	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_242] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:91) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.RegistryObject.isPresent(RegistryObject.java:115) ~[?:?] {re:classloading}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_242] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_242] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_242] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_242] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546) ~[?:1.8.0_242] {}
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:1.8.0_242] {}
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505) ~[?:1.8.0_242] {}
	at net.minecraftforge.lex.cfd.CobbleForDays.colorGeneratorBlockWater(CobbleForDays.java:107) ~[?:1.1.1] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.1] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243) ~[?:?] {re:classloading}
	at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_242] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:198) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[1.15.2-forge-31.1.1.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.1.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:228)
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:91)
	at net.minecraftforge.fml.RegistryObject.isPresent(RegistryObject.java:115)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at net.minecraftforge.lex.cfd.CobbleForDays.colorGeneratorBlockWater(CobbleForDays.java:107)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243)
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:198)
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 5.5.2
	Java Version: 1.8.0_242, Debian
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Debian
	Memory: 1295477256 bytes (1235 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.1
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotori_scala@2.13.1-build-6
	Mod List: 
		followingvillagers-1.15.2-1.4.0.jar Following Villagers {followingvillagers@1.15.2-1.4.0 CREATE_REGISTRIES}
		AdditionalEnchantedMiner-1.15.1-15.2.0.jar QuarryPlus {quarryplus@15.2.0 CREATE_REGISTRIES}
		chanceglobe-1.15.2-v1.3.2.jar Chance Globe {chanceglobe@v1.3.2 CREATE_REGISTRIES}
		prefab-1.5.0.0.jar Prefab {prefab@1.5.0.0 CREATE_REGISTRIES}
		EditSign-1.15.2-2.0.0+7.jar Edit Sign {edit_sign@2.0.0+7 CREATE_REGISTRIES}
		ProjectE-1.15.2-PE1.0.2B.jar ProjectE {projecte@1.0.2B CREATE_REGISTRIES}
		planttech2-0.01.07.jar PlantTech 2 {planttech2@0.01.07 CREATE_REGISTRIES}
		IndustrialAgriculture[Core]-1.15.2-1.5.4.jar Industrial Agriculture {industrialagriculture@1.15.2-1.5.4 CREATE_REGISTRIES}
		music_player-1.15.2-2.0.10.61.jar Music Player {musicplayer@2.0.10.61 CREATE_REGISTRIES}
		rsgauges-1.15.2-1.2.1.jar Gauges and Switches {rsgauges@1.2.1 CREATE_REGISTRIES}
		IronJetpacks-1.15.2-3.0.0.jar Iron Jetpacks {ironjetpacks@3.0.0 CREATE_REGISTRIES}
		XaerosWorldMap_1.5.5_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.5 CREATE_REGISTRIES}
		Controlling-6.1.1.jar Controlling {controlling@6.1.1 CREATE_REGISTRIES}
		BetterSprinting-1.15.2-v3.1.0.jar Better Sprinting {bettersprinting@3.1.0 CREATE_REGISTRIES}
		ReAuth-1.14-3.8.0.jar ReAuth {reauth@3.8.0 CREATE_REGISTRIES}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 CREATE_REGISTRIES}
		dankstorage-2.5.jar Dank Storage {dankstorage@2.5 ERROR}
		sneakthroughberries-1.15.2-20w06a-1.0.1.jar Sneak Through Berries {sneakthroughberries@1.15.2-20w06a-1.0.1 CREATE_REGISTRIES}
		rangedpumps-0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 CREATE_REGISTRIES}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 CREATE_REGISTRIES}
		u_team_core-1.15.2-2.10.4.153.jar U Team Core {uteamcore@2.10.4.153 CREATE_REGISTRIES}
		Apotheosis-1.15.2-3.0.4.jar Apotheosis {apotheosis@3.0.4 CREATE_REGISTRIES}
		LightingWand-1.15.2-1.4.2.jar Lighting Wand {lightingwand@1.4.2 CREATE_REGISTRIES}
		Morpheus-1.15.2-4.2.47.jar Morpheus {morpheus@version CREATE_REGISTRIES}
		advancedtools-1.15.2-1.0.1.jar Advanced Tools {advancedtools@1.15.2-1.0.1 CREATE_REGISTRIES}
		MekanismGenerators-1.15.2-9.9.9.401.jar Mekanism: Generators {mekanismgenerators@9.9.9 CREATE_REGISTRIES}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version CREATE_REGISTRIES}
		WaterStrainer-1.15.1-8.0.0.jar Water Strainer {waterstrainer@1.15.1-8.0.0 CREATE_REGISTRIES}
		speedyhoppers-1.15.2-2.jar Speedy Hoppers {speedyhoppers@1.15.2-2 CREATE_REGISTRIES}
		SnowRealMagic-1.15.2-1.7.2.jar Snow! Real Magic! {snowrealmagic@1.7.2 CREATE_REGISTRIES}
		shulkerbox-1.9.1.jar Advanced Shulkerboxes {shulkerbox@1.9.1 CREATE_REGISTRIES}
		ExpOreMod-1.15.2-1.1.jar Exp Ore Block {exp_ore@1.1 CREATE_REGISTRIES}
		TOOLKIT-1.15.2-1.6.4.jar Tool Kit {toolkit@1.15.2-1.6.4 CREATE_REGISTRIES}
		MysticalAgradditions-1.15.2-3.0.0.jar Mystical Agradditions {mysticalagradditions@3.0.0 CREATE_REGISTRIES}
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 CREATE_REGISTRIES}
		quartz-chests-1.1.0.5.jar Quartz Chests {quartzchests@1.1.0.5 CREATE_REGISTRIES}
		mcw-bridges-1.0.3-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.3 CREATE_REGISTRIES}
		lightestlampsmod-3.3.0.jar Lightest Lamps {lightestlamp@3.3.0 CREATE_REGISTRIES}
		industrial-foregoing-1.15.2-2.2.1-f27c515.jar Industrial Foregoing {industrialforegoing@2.2.1 CREATE_REGISTRIES}
		angermanagement-1.15.2-1.0.0.jar Anger Management Mod {angermanagement@1.15.2-1.0.0 CREATE_REGISTRIES}
		useful_backpacks-1.15.2-1.9.3.62.jar Useful Backpacks {usefulbackpacks@1.9.3.62 CREATE_REGISTRIES}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 CREATE_REGISTRIES}
		entangled-1.1.4-mc1.15.2.jar Entangled {entangled@1.1.2 CREATE_REGISTRIES}
		smartdispensers-1.0.jar Smart Dispensers {smartdispensers@1 CREATE_REGISTRIES}
		BiomesOPlenty-1.15.2-10.0.0.326-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.322 CREATE_REGISTRIES}
		valkyrielib-1.15.2-3.0.2.1.jar ValkyrieLib {valkyrielib@1.15.2-3.0.2.1 CREATE_REGISTRIES}
		simplechunkloaders-1.15.2-1.0.2.0.jar Simple Chunk Loaders {simplechunkloaders@NONE CREATE_REGISTRIES}
		valhelsia_structures-1.15.1-0.0.1.jar Valhelsia Structures {valhelsia_structures@1.15.1-0.0.1 CREATE_REGISTRIES}
		wtbw_lib-1.15.2-1.0.8.jar WTBW Library {wtbw_lib@1.0.8 CREATE_REGISTRIES}
		tgcropesmod-1.15.2-1.1.1.jar Ropes Mod {tgcropesmod@1.15.2-1.1.1 CREATE_REGISTRIES}
		horsemodifiers-1.15.2-1.2.jar Horse Modifiers {horsemodifiers@1.2 CREATE_REGISTRIES}
		simplybackpacks-1.15.2-1.3.0.jar Simply Backpacks {simplybackpacks@1.15.2-1.3.0 CREATE_REGISTRIES}
		randomenchants-3.1.0.jar Random Enchants {randomenchants@3.1.0 CREATE_REGISTRIES}
		portality-1.15.2-2.1.2-aaa257f.jar Portality {portality@2.1.2 CREATE_REGISTRIES}
		curios-FORGE-1.15.2-2.0-beta2.jar Curios API {curios@FORGE-1.15.2-2.0-beta2 CREATE_REGISTRIES}
		Clay WorldGen-1.1.0-1.15.1.jar Clay WorldGen {clayworldgen@version CREATE_REGISTRIES}
		RingOfBlink-1.15.2-1.1.12.jar Ring of Blink {ring_of_blink@1.1.12 CREATE_REGISTRIES}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 CREATE_REGISTRIES}
		RingOfMiner-1.15.2-1.1.12.jar Ring of Miner {ring_of_miner@1.1.12 CREATE_REGISTRIES}
		wtbw_tools-1.15.2-1.0.6.jar WTBW Tools {wtbw_tools@1.0.6 CREATE_REGISTRIES}
		OreExcavation-1.7.149.jar Ore Excavation {oreexcavation@NONE CREATE_REGISTRIES}
		tanknull-1.7.jar Tank Null {tanknull@1.7 CREATE_REGISTRIES}
		angelring-1.15.2-1.2.0.jar Angel Ring {angelring@1.2.0 CREATE_REGISTRIES}
		f2l-0.3.1.jar Flesh 2 Leather {f2l@0.3.1 CREATE_REGISTRIES}
		additionalevents-1.0a.jar Additional Events {additionalevents@1.0a CREATE_REGISTRIES}
		lostcities-1.15-3.0.0-alpha.jar LostCities {lostcities@1.15-3.0.0-alpha CREATE_REGISTRIES}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 CREATE_REGISTRIES}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 CREATE_REGISTRIES}
		Gobber2-1.15.2-2.2.41.jar Gobber 2 {gobber2@2.2.41 CREATE_REGISTRIES}
		tombstone-4.2.2-1.15.2.jar Corail Tombstone {tombstone@4.2.2 CREATE_REGISTRIES}
		RingOfEnderchest-1.15.2-1.1.12.jar Ring of Enderchest {ring_of_enderchest@1.1.12 CREATE_REGISTRIES}
		PowderPower-1.15.2-3.1.29.jar Powder Power {powder_power@3.1.29 CREATE_REGISTRIES}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c CREATE_REGISTRIES}
		MekanismTools-1.15.2-9.9.9.401.jar Mekanism: Tools {mekanismtools@9.9.9 CREATE_REGISTRIES}
		ChunkNoGoByeBye-1.15.2-1.2.0.jar ChunkNoGoByeBye {chunknogobyebye@1.15.2-1.2.0 CREATE_REGISTRIES}
		globalxp-1.15.2-v1.4.11.jar Global XP {globalxp@v1.4.11 CREATE_REGISTRIES}
		betterwithminecolonies-1.15.2-1.13.14.jar Better With Minecolonies {betterwithminecolonies@1.15.2-1.13.14 CREATE_REGISTRIES}
		CobbleForDays-1.1.1.jar Cobble For Days {cobblefordays@1.1.1 CREATE_REGISTRIES}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 CREATE_REGISTRIES}
		Disenchanting_(forge)_1.15.2-1.2.0.jar Disenchanting {disenchanting@1.2.0 CREATE_REGISTRIES}
		CleanView-1.15.2-v1.jar CleanView {cleanview@1.15.2-v1 CREATE_REGISTRIES}
		blockactions-0.1-1.15.2.jar Block Actions {blockactions@0.0.1-1.15.2 CREATE_REGISTRIES}
		Treasure-Bags-1.15.2-1.2.0+20.jar Treasure Bags {treasurebags@1.2.0+20 CREATE_REGISTRIES}
		BetterAdvancements-1.15.2-0.1.0.96.jar Better Advancements {betteradvancements@0.1.0.96 CREATE_REGISTRIES}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 CREATE_REGISTRIES}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 CREATE_REGISTRIES}
		Ma-Enchants-1.15.2-3.0.0.jar Ma Enchants {ma-enchants@1.15.2-3.0.0 CREATE_REGISTRIES}
		Cucumber-1.15.2-3.0.1.jar Cucumber Library {cucumber@3.0.1 CREATE_REGISTRIES}
		mining-helmet-1.15.2-1.0.6.jar Mining Helmet {mining_helmet@1.0.6 CREATE_REGISTRIES}
		craftingstation-3.0.4.jar Crafting Station {craftingstation@3.0.4 CREATE_REGISTRIES}
		snad-1.8.3.3a-1.15.2.jar Snad {snad@1.8.3.3a CREATE_REGISTRIES}
		Overloaded-1.15.2-0.0.81.jar Overloaded {overloaded@1.15.2-0.0.80 CREATE_REGISTRIES}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 CREATE_REGISTRIES}
		metalbarrels-2.1.jar Metal Barrels {metalbarrels@2.1 CREATE_REGISTRIES}
		longfallboots-1.4.0b.jar Long Fall Boots {longfallboots@1.4.0b CREATE_REGISTRIES}
		Mekanism-1.15.2-9.9.9.401.jar Mekanism {mekanism@9.9.9 CREATE_REGISTRIES}
		AutoDropper-1.15.1-6.0.0.jar Auto Dropper {autodropper@1.15.1-6.0.0 CREATE_REGISTRIES}
		RingOfRepair-1.15.2-1.1.13.jar Ring of Repair {ring_of_repair@1.1.13 CREATE_REGISTRIES}
		LightOverlay-4.2.jar Light Overlay Forge {lightoverlay-forge@4.2 CREATE_REGISTRIES}
		EnderBags-1.15.1-5.0.0.jar Ender Bags {ender_bags@5.0.0 CREATE_REGISTRIES}
		SimpleStorageNetwork-1.15.2-0.2.4.jar Simple Storage Network {storagenetwork@1.15.2-0.2.4 CREATE_REGISTRIES}
		SereneSeasons-1.15.2-3.0.0.57-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.57 CREATE_REGISTRIES}
		gardentools-1.15.2-1.0.0.jar Garden Tools {gardentools@1.15.2-1.0.0 CREATE_REGISTRIES}
		engineerstools-1.15.2-1.0.6-b2.jar Engineer's Tools {engineerstools@1.0.6-b2 CREATE_REGISTRIES}
		DungeonCrawl-1.15.2-1.6.1.jar Dungeon Crawl {dungeoncrawl@1.6.1 CREATE_REGISTRIES}
		RingOfTeleport-1.15.2-1.1.13.jar Ring of Teleport {ring_of_teleport@1.1.13 CREATE_REGISTRIES}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 CREATE_REGISTRIES}
		mcjtylib-1.15-4.0.1-alpha.jar McJtyLib {mcjtylib@1.15-4.0.1-alpha CREATE_REGISTRIES}
		rftoolsbase-1.15-1.0.0-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.0-alpha CREATE_REGISTRIES}
		rftoolsstorage-1.15-1.0.1-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.1-alpha CREATE_REGISTRIES}
		ClickMachine-1.15.2-3.0.1.jar Click Machine {clickmachine@3.0.1 CREATE_REGISTRIES}
		travellersboots-1.15.2-1.3.2.jar Traveller's Boots {travellersboots@1.3.1 CREATE_REGISTRIES}
		environmentalcreepers-forge-1.15.2-1.6.1.jar Environmental Creepers {environmentalcreepers@1.6.1 CREATE_REGISTRIES}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 CREATE_REGISTRIES}
		PackingTape-1.15.2-0.9.5.jar Packing Tape {packingtape@0.9.5 CREATE_REGISTRIES}
		endercompass-2.0.jar Ender Compass {endercompass@2.0 CREATE_REGISTRIES}
		CraftTweaker-1.15.1-6.0.0.5.jar CraftTweaker {crafttweaker@6.0.0.5 CREATE_REGISTRIES}
		extradisks-1.15.1-1.2.jar Extra Disks {extradisks@1.15.1-1.2 CREATE_REGISTRIES}
		campfiretorches-1.15.2-1.0.2.jar Campfire Torches {campfiretorches@1.15.2-1.0.2 CREATE_REGISTRIES}
		forge-1.15.2-31.1.1-universal.jar Forge {forge@31.1.1 CREATE_REGISTRIES}
		PassthroughSigns-1.15.1-2.3.2.jar Passthrough Signs {passthroughsigns@1.15.1-2.3.2 CREATE_REGISTRIES}
		wtbw_core-1.15.2-1.0.9.jar WTBW Core {wtbw_core@1.0.9 CREATE_REGISTRIES}
		MysticalAgriculture-1.15.2-3.0.0.jar Mystical Agriculture {mysticalagriculture@3.0.0 CREATE_REGISTRIES}
		coffeebreak-1.5.jar Softcat's Coffee Break {coffeebreak@1.5 CREATE_REGISTRIES}
		forge-1.15.2-31.1.1-client.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		rftoolsutility-1.15-2.0.0-alpha.jar RFToolsUtility {rftoolsutility@1.15-2.0.0-alpha CREATE_REGISTRIES}
		clockout-1.15.2-1.0.0.jar Clockout {clockout@1.15.2-1.0.0 CREATE_REGISTRIES}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 CREATE_REGISTRIES}
		ToolBelt-1.15.2-1.14.0.jar Tool Belt {toolbelt@1.14.0 CREATE_REGISTRIES}
		titanium-1.15.2-2.3.6.jar Titanium {titanium@2.3.6 CREATE_REGISTRIES}
		SilentLib-1.15.2-4.6.0+48.jar Silent Lib {silentlib@4.6.0+48 CREATE_REGISTRIES}
		wtbw_machines-1.15.2-1.0.7.jar WTBW Machines {wtbw_machines@1.0.7 CREATE_REGISTRIES}
		RingOfGrowth-1.15.2-1.1.14.jar Ring of Growth {ring_of_growth@1.1.14 CREATE_REGISTRIES}
		theplopper-1.15.1-v1.3.jar The Plopper {theplopper@v1.3 CREATE_REGISTRIES}
		forbidden_arcanus-1.15.2-1.0-beta-4.jar Forbidden & Arcanus {forbidden_arcanus@1.15.1-1.0-beta-1 CREATE_REGISTRIES}
		packedup-1.0.2-mc1.15.2.jar PackedUp {packedup@1.0 CREATE_REGISTRIES}
		LargeFluidTank-15.2.2.jar FluidTank {fluidtank@15.2.2 CREATE_REGISTRIES}
		rftoolsbuilder-1.15-2.0.0-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.0-alpha CREATE_REGISTRIES}
		dimdungeons-1.03-forge-1.15.2.jar Dimensional Dungeons {dimdungeons@1.14.4-1.03 CREATE_REGISTRIES}
		flux-4.7.2.jar Flux {flux@4.7.2 CREATE_REGISTRIES}
		fl-3.0.2.jar Flux Library {fl@3.0.2 CREATE_REGISTRIES}
		Xaeros_Minimap_20.3.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.3.0 CREATE_REGISTRIES}
		ShulkerTooltip-1.9.2.jar Shulker Tooltip {shulkertooltip@1.9.2 CREATE_REGISTRIES}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 CREATE_REGISTRIES}
		torcherino-10.0.1.jar Torcherino {torcherino@10.0.1 CREATE_REGISTRIES}
		backpacked-1.4.1-1.15.2.jar Backpacked {backpacked@1.4.1 CREATE_REGISTRIES}
		vanillahammers-1.15.1-1.0.jar Vanilla Hammers {vanillahammers@1.15.1-1.0 CREATE_REGISTRIES}
		tubesreloaded-1.15.2-1.2.0.jar Tubes Reloaded {tubesreloaded@1.15.2-1.2.0 CREATE_REGISTRIES}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 CREATE_REGISTRIES}
		engineersdecor-1.15.2-1.0.19-b3.jar Engineer's Decor {engineersdecor@1.0.19-b3 CREATE_REGISTRIES}
		moredragoneggs-1.0.jar More Dragon Eggs {moredragoneggs@1.0 CREATE_REGISTRIES}
		RingOfAttraction-1.15.2-1.1.15.jar Ring of Attraction {ring_of_attraction@1.1.15 CREATE_REGISTRIES}
		Aquaculture-1.15.2-2.0.8.jar Aquaculture 2 {aquaculture@1.15.2-2.0.8 CREATE_REGISTRIES}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 CREATE_REGISTRIES}
		waterworks-1.15.2-2.1.0.jar Waterworks {waterworks@1.15.2-2.1.0 CREATE_REGISTRIES}
		Industrial Agriculture[Mekanism]-1.15.2-1.5.2.jar Industrial Agriculture Plugin-Mekanism {iapmekanism@1.15.2-1.5.2 CREATE_REGISTRIES}
		CHAS v1.3 for 1.15.jar Craftable Horse Armour {craftablehorsearmour@1.3 CREATE_REGISTRIES}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 CREATE_REGISTRIES}
		Ma-Essentials-1.15.2-3.0.0.jar Ma Essentials {ma-essentials@1.15.2-3.0.0 CREATE_REGISTRIES}
		SolarGeneration-1.15.2-1.2.0.jar Solar Generation {solargeneration@1.2.0 CREATE_REGISTRIES}
		parachutemod-1.15.2-2.3.2-471.jar Parachute Mod NG {parachutemod@1.15.2-2.3.2-471 CREATE_REGISTRIES}
		SuperTools-1.1_1.15.2.jar Super Tools {supertools@1.1 CREATE_REGISTRIES}
		Omega Craft 4.0.9 - 1.15.2.jar Omega Craft {omegacraft@1.0 CREATE_REGISTRIES}
		lootbagmod-1.15.1-1.3.jar Loot Bag Mod {lootbagmod@1.15.1-1.3 CREATE_REGISTRIES}
		draw_bridge-1.15.2-1.4.2.17.jar Draw Bridge {drawbridge@1.4.2.17 CREATE_REGISTRIES}
		xptome-1.15.1-v1.1.4.jar XP Tome {xpbook@v1.1.4 CREATE_REGISTRIES}
		bigbuckets-1.1.0.jar BigBuckets {bigbuckets@1.1.0 CREATE_REGISTRIES}
	Launched Version: 1.15.2-forge-31.1.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 440.59, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

**Comment by Seegras** [comment]
Addendum, modpack is now online, without dank storage, sadly, but you can add it manually to test https://www.curseforge.com/minecraft/modpacks/a-roving/files

**Comment by Tfarcenim** [comment]
Did you install mixin?

**Comment by Tfarcenim** [comment]
No, no you didn't judging by the crash report so closing as user error, if it still crashes after installing mixin open a new issue.

**Comment by Seegras** [comment]
Thank you. It works. Except: 
> "The status of the file A-Roving-1.0.8.zip (A-Roving) has been changed to Rejected
> Notes:  The following files do not appear to belong to any mods on the approved Non-CurseForge list:
> overrides/mods/MixinBootstrap-1.0.2.jar
> Please see https://authors.curseforge.com/knowledge-base/game-specific-support/3279-non-curseforge-mods for full details."

Don't even bother to look it up, of course it *IS* on the approved list. *sigh*

**Comment by Tfarcenim** [comment]
backdate to 1.0.1 until the author adds the new file to the approved list
