### ISSUE TITLE
[1.12.2 Server] Error executing task when pressing any keybind fron them mod

### ISSUE THREAD

**Issue by Desempregago** [Tfarcenim/Dank-Storage#53]
Everytime I press a keybind whether be it void or autopickup toggle, it gives out on the console a 
```
[net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_252]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_252]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at com.tfar.dankstorage.util.Utils.toggle(Utils.java:39) ~[Utils.class:?]
	at com.tfar.dankstorage.network.CMessageToggle$Handler.handle(CMessageToggle.java:58) ~[CMessageToggle$Handler.class:?]
	at com.tfar.dankstorage.network.CMessageToggle$Handler.lambda$onMessage$0(CMessageToggle.java:47) ~[CMessageToggle$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

Running 1.4-pre-11 (1.12.2)
Forge 2854

**Comment by Desempregago** [comment]
PS: The server doesn't crash, but the Dank doesn't do anything apart from its basic functionality (storage).

**Comment by Tfarcenim** [comment]
yeah, don't use it in 1.12, it sucks
