### ISSUE TITLE
Unable to join a multiplayer server - Internal Server Error

### ISSUE THREAD

**Issue by MechanosG** [Tfarcenim/Dank-Storage#96]
Heya.  Awesome mod.  Unfortunately I think something broke.  Short version, I'm currently testing a 1.16.4 fabric modpack on a dedicated server without about 5 players currently, containing dankstorage-1.9a-1.16.3.jar, and things were working fine.  Then suddenly out of nowhere, I am no longer able to join the server.  My client tells me Internal Server Error, and my client console shows absolutely nothing.  So I intarweb searched the issue, and the most common reported thing is messed up player data.  So I asked the server host to send me the server's playerdata folder, replicated the server locally, then added the playerdata.  Sure enough, even in a fresh world, I get the same Internal Server Error.  Only, now that I have access to the server, I'm getting this in the server console - 

```
[00:25:15] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:3248
net.minecraft.class_148: Loading entity NBT
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7) ~[?:?]
	at net.minecraft.entity.Entity.fromTag(Entity:1663) ~[?:?]
	at net.minecraft.world.WorldSaveHandler.loadPlayerData(WorldSaveHandler:57) ~[?:?]
	at net.minecraft.server.PlayerManager.loadPlayerData(PlayerManager:344) ~[?:?]
	at net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager:138) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.acceptPlayer(ServerLoginNetworkHandler:113) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.redirect$bpk000$handlePlayerJoin(ServerLoginNetworkHandler:562) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.tick(ServerLoginNetworkHandler:65) ~[?:?]
	at net.minecraft.network.ClientConnection.tick(ClientConnection:228) ~[?:?]
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:173) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:882) ~[intermediary-server.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:312) ~[?:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.NullPointerException
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7) ~[?:?]
	at net.minecraft.item.ItemStack.handler$zmo000$areTagsEqualReturn1(ItemStack:6655) ~[?:?]
	at net.minecraft.item.ItemStack.areTagsEqual(ItemStack:383) ~[?:?]
	at tfar.dankstorage.event.MixinHooks.areItemStacksCompatible(MixinHooks.java:227) ~[dankstorage-1.9a-1.16.3.jar:?]
	at tfar.dankstorage.event.MixinHooks.doesItemStackExist(MixinHooks.java:232) ~[dankstorage-1.9a-1.16.3.jar:?]
	at tfar.dankstorage.event.MixinHooks.voidPickup(MixinHooks.java:150) ~[dankstorage-1.9a-1.16.3.jar:?]
	at tfar.dankstorage.event.MixinHooks.onItemPickup(MixinHooks.java:132) ~[dankstorage-1.9a-1.16.3.jar:?]
	at tfar.dankstorage.event.MixinHooks.interceptItem(MixinHooks.java:47) ~[dankstorage-1.9a-1.16.3.jar:?]
	at net.minecraft.entity.player.PlayerInventory.handler$bdi000$interceptItems(PlayerInventory:2690) ~[?:?]
	at net.minecraft.entity.player.PlayerInventory.insertStack(PlayerInventory) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.giveItemStack(PlayerEntity:1907) ~[?:?]
	at dev.emi.trinkets.api.PlayerTrinketComponent.fromTag(PlayerTrinketComponent.java:42) ~[trinkets-2.6.7.jar:?]
	at nerdhub.cardinal.components.api.util.container.AbstractComponentContainer.fromTag(AbstractComponentContainer.java:180) ~[f37fc192-c514-48a1-9d3c-a4d8ea68d0c7.jar:?]
	at net.minecraft.entity.Entity.handler$bdp000$fromTag(Entity:8692) ~[?:?]
	at net.minecraft.entity.Entity.fromTag(Entity:1654) ~[?:?]
	... 14 more
```

I'm not entirely sure, but it appears to be dank storage related.  There's no crash, so no crash log.  Deleting the playerdata with my UUID allows me to join.  I haven't tried to edit the NBT to try and narrow down if it's a specific item in one of my danks, although I'm thinking about it.  If you need any extra information, please let me know.  I'd give you a mod list, but the pack is up to about 140 mods and I'm not sure how to easily export a list of what mods I'm using without a crashlog.

**Comment by Tfarcenim** [comment]
throw this on the server and send over the report https://modrinth.com/mod/mixintrace

**Comment by MechanosG** [comment]
Alright, will do.

**Comment by MechanosG** [comment]
Does that mod only affect crash reports?  Nothing is technically crashing, so no crash report is made.  I added mixintrace to both the client and the server, then connected.  But the error in console looks identical.

```
[13:14:38] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:1476
net.minecraft.class_148: Loading entity NBT
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7) ~[?:?]
	at net.minecraft.entity.Entity.fromTag(Entity:1663) ~[?:?]
	at net.minecraft.world.WorldSaveHandler.loadPlayerData(WorldSaveHandler:57) ~[?:?]
	at net.minecraft.server.PlayerManager.loadPlayerData(PlayerManager:344) ~[?:?]
	at net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager:138) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.acceptPlayer(ServerLoginNetworkHandler:113) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.redirect$bpl000$handlePlayerJoin(ServerLoginNetworkHandler:562) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.tick(ServerLoginNetworkHandler:65) ~[?:?]
	at net.minecraft.network.ClientConnection.tick(ClientConnection:228) ~[?:?]
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:173) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:882) ~[intermediary-server.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:312) ~[?:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.NullPointerException
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7) ~[?:?]
	at net.minecraft.item.ItemStack.handler$zmo000$areTagsEqualReturn1(ItemStack:6655) ~[?:?]
	at net.minecraft.item.ItemStack.areTagsEqual(ItemStack:383) ~[?:?]
	at tfar.dankstorage.event.MixinHooks.areItemStacksCompatible(MixinHooks.java:227) ~[dankstorage-1.9a-1.16.3.jar:?]
	at tfar.dankstorage.event.MixinHooks.doesItemStackExist(MixinHooks.java:232) ~[dankstorage-1.9a-1.16.3.jar:?]
	at tfar.dankstorage.event.MixinHooks.voidPickup(MixinHooks.java:150) ~[dankstorage-1.9a-1.16.3.jar:?]
	at tfar.dankstorage.event.MixinHooks.onItemPickup(MixinHooks.java:132) ~[dankstorage-1.9a-1.16.3.jar:?]
	at tfar.dankstorage.event.MixinHooks.interceptItem(MixinHooks.java:47) ~[dankstorage-1.9a-1.16.3.jar:?]
	at net.minecraft.entity.player.PlayerInventory.handler$bdi000$interceptItems(PlayerInventory:2690) ~[?:?]
	at net.minecraft.entity.player.PlayerInventory.insertStack(PlayerInventory) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.giveItemStack(PlayerEntity:1907) ~[?:?]
	at dev.emi.trinkets.api.PlayerTrinketComponent.fromTag(PlayerTrinketComponent.java:42) ~[trinkets-2.6.7.jar:?]
	at nerdhub.cardinal.components.api.util.container.AbstractComponentContainer.fromTag(AbstractComponentContainer.java:180) ~[d0fe2d0d-1be8-4180-b433-129f936b3e6a.jar:?]
	at net.minecraft.entity.Entity.handler$bdp000$fromTag(Entity:8692) ~[?:?]
	at net.minecraft.entity.Entity.fromTag(Entity:1654) ~[?:?]
	... 14 more
```
Edit: Tested without not enough crashes just to see if it changed the output at all, but it didn't.

**Comment by Tfarcenim** [comment]
Damn, didn't realize it wasn't an actual crash, nothing I can do then as I don't know what mod that mixin belongs to
